name: Laravel Local
values:
  - key: baseUrl
    value: 'http://localhost'
    enabled: true
    type: default
  - key: sanctum_token
    value: ''
    enabled: true
    type: secret
  - key: customer_id
    value: '1'
    enabled: true
    type: default
  - key: invoice_id
    value: '1'
    enabled: true
    type: default
